#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanPhap.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietSo(ChiTietSo instance);
    partial void UpdateChiTietSo(ChiTietSo instance);
    partial void DeleteChiTietSo(ChiTietSo instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::VanPhap.Properties.Settings.Default.DataSourceConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DangLe> DangLes
		{
			get
			{
				return this.GetTable<DangLe>();
			}
		}
		
		public System.Data.Linq.Table<PhatTu> PhatTus
		{
			get
			{
				return this.GetTable<PhatTu>();
			}
		}
		
		public System.Data.Linq.Table<Sao> Saos
		{
			get
			{
				return this.GetTable<Sao>();
			}
		}
		
		public System.Data.Linq.Table<So> Sos
		{
			get
			{
				return this.GetTable<So>();
			}
		}
		
		public System.Data.Linq.Table<LoaiLe> LoaiLes
		{
			get
			{
				return this.GetTable<LoaiLe>();
			}
		}
		
		public System.Data.Linq.Table<LoaiSo> LoaiSos
		{
			get
			{
				return this.GetTable<LoaiSo>();
			}
		}
		
		public System.Data.Linq.Table<Han> Hans
		{
			get
			{
				return this.GetTable<Han>();
			}
		}
		
		public System.Data.Linq.Table<Nam> Nams
		{
			get
			{
				return this.GetTable<Nam>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietSo> ChiTietSos
		{
			get
			{
				return this.GetTable<ChiTietSo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangLe")]
	public partial class DangLe
	{
		
		private string _ID;
		
		private System.Nullable<int> _IDLoaiLe;
		
		private System.Nullable<System.DateTime> _ThoiDiem;
		
		private System.Nullable<int> _IDSo;
		
		public DangLe()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiLe", DbType="Int")]
		public System.Nullable<int> IDLoaiLe
		{
			get
			{
				return this._IDLoaiLe;
			}
			set
			{
				if ((this._IDLoaiLe != value))
				{
					this._IDLoaiLe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiDiem
		{
			get
			{
				return this._ThoiDiem;
			}
			set
			{
				if ((this._ThoiDiem != value))
				{
					this._ThoiDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSo", DbType="Int")]
		public System.Nullable<int> IDSo
		{
			get
			{
				return this._IDSo;
			}
			set
			{
				if ((this._IDSo != value))
				{
					this._IDSo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhatTu")]
	public partial class PhatTu
	{
		
		private int _ID;
		
		private string _HoTen;
		
		private string _PhapDanh;
		
		private string _DiaChi;
		
		private string _NguyenQuan;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _IDNamSinh;
		
		public PhatTu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhapDanh", DbType="NVarChar(50)")]
		public string PhapDanh
		{
			get
			{
				return this._PhapDanh;
			}
			set
			{
				if ((this._PhapDanh != value))
				{
					this._PhapDanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguyenQuan", DbType="NVarChar(MAX)")]
		public string NguyenQuan
		{
			get
			{
				return this._NguyenQuan;
			}
			set
			{
				if ((this._NguyenQuan != value))
				{
					this._NguyenQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNamSinh", DbType="Int")]
		public System.Nullable<int> IDNamSinh
		{
			get
			{
				return this._IDNamSinh;
			}
			set
			{
				if ((this._IDNamSinh != value))
				{
					this._IDNamSinh = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sao")]
	public partial class Sao
	{
		
		private System.Nullable<int> _ID;
		
		private string _Sao1;
		
		public Sao()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Sao", Storage="_Sao1", DbType="NVarChar(50)")]
		public string Sao1
		{
			get
			{
				return this._Sao1;
			}
			set
			{
				if ((this._Sao1 != value))
				{
					this._Sao1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.So")]
	public partial class So
	{
		
		private int _ID;
		
		private System.Nullable<int> _IDChuBai;
		
		private System.Nullable<System.DateTime> _NgayLapSo;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<int> _IDLoaiSo;
		
		public So()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChuBai", DbType="Int")]
		public System.Nullable<int> IDChuBai
		{
			get
			{
				return this._IDChuBai;
			}
			set
			{
				if ((this._IDChuBai != value))
				{
					this._IDChuBai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapSo", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLapSo
		{
			get
			{
				return this._NgayLapSo;
			}
			set
			{
				if ((this._NgayLapSo != value))
				{
					this._NgayLapSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this._NgayCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiSo", DbType="Int")]
		public System.Nullable<int> IDLoaiSo
		{
			get
			{
				return this._IDLoaiSo;
			}
			set
			{
				if ((this._IDLoaiSo != value))
				{
					this._IDLoaiSo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiLe")]
	public partial class LoaiLe
	{
		
		private System.Nullable<int> _ID;
		
		private string _GhiChu;
		
		public LoaiLe()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSo")]
	public partial class LoaiSo
	{
		
		private System.Nullable<double> _ID;
		
		private string _GhiChu;
		
		private string _GhiChu_Unicode;
		
		public LoaiSo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Float")]
		public System.Nullable<double> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu_Unicode", DbType="NVarChar(255)")]
		public string GhiChu_Unicode
		{
			get
			{
				return this._GhiChu_Unicode;
			}
			set
			{
				if ((this._GhiChu_Unicode != value))
				{
					this._GhiChu_Unicode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Han")]
	public partial class Han
	{
		
		private System.Nullable<double> _ID;
		
		private string _Han1;
		
		private string _Han_Unicode;
		
		public Han()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Float")]
		public System.Nullable<double> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Han", Storage="_Han1", DbType="NVarChar(255)")]
		public string Han1
		{
			get
			{
				return this._Han1;
			}
			set
			{
				if ((this._Han1 != value))
				{
					this._Han1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Han_Unicode", DbType="NVarChar(255)")]
		public string Han_Unicode
		{
			get
			{
				return this._Han_Unicode;
			}
			set
			{
				if ((this._Han_Unicode != value))
				{
					this._Han_Unicode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nam")]
	public partial class Nam
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _NamDL;
		
		private string _NamAL;
		
		public Nam()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamDL", DbType="Int")]
		public System.Nullable<int> NamDL
		{
			get
			{
				return this._NamDL;
			}
			set
			{
				if ((this._NamDL != value))
				{
					this._NamDL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamAL", DbType="NVarChar(50)")]
		public string NamAL
		{
			get
			{
				return this._NamAL;
			}
			set
			{
				if ((this._NamAL != value))
				{
					this._NamAL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietSo")]
	public partial class ChiTietSo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _IDSo;
		
		private string _GioiTinh;
		
		private System.Nullable<double> _IDNamSinh;
		
		private string _HoTen;
		
		private string _PhapDanh;
		
		private string _Sao;
		
		private string _Han;
		
		private string _Tuoi;
		
		private int _IDD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSoChanging(System.Nullable<int> value);
    partial void OnIDSoChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnIDNamSinhChanging(System.Nullable<double> value);
    partial void OnIDNamSinhChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnPhapDanhChanging(string value);
    partial void OnPhapDanhChanged();
    partial void OnSaoChanging(string value);
    partial void OnSaoChanged();
    partial void OnHanChanging(string value);
    partial void OnHanChanged();
    partial void OnTuoiChanging(string value);
    partial void OnTuoiChanged();
    partial void OnIDDChanging(int value);
    partial void OnIDDChanged();
    #endregion
		
		public ChiTietSo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSo", DbType="Int")]
		public System.Nullable<int> IDSo
		{
			get
			{
				return this._IDSo;
			}
			set
			{
				if ((this._IDSo != value))
				{
					this.OnIDSoChanging(value);
					this.SendPropertyChanging();
					this._IDSo = value;
					this.SendPropertyChanged("IDSo");
					this.OnIDSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNamSinh", DbType="Float")]
		public System.Nullable<double> IDNamSinh
		{
			get
			{
				return this._IDNamSinh;
			}
			set
			{
				if ((this._IDNamSinh != value))
				{
					this.OnIDNamSinhChanging(value);
					this.SendPropertyChanging();
					this._IDNamSinh = value;
					this.SendPropertyChanged("IDNamSinh");
					this.OnIDNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(255)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhapDanh", DbType="NVarChar(255)")]
		public string PhapDanh
		{
			get
			{
				return this._PhapDanh;
			}
			set
			{
				if ((this._PhapDanh != value))
				{
					this.OnPhapDanhChanging(value);
					this.SendPropertyChanging();
					this._PhapDanh = value;
					this.SendPropertyChanged("PhapDanh");
					this.OnPhapDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sao", DbType="NVarChar(50)")]
		public string Sao
		{
			get
			{
				return this._Sao;
			}
			set
			{
				if ((this._Sao != value))
				{
					this.OnSaoChanging(value);
					this.SendPropertyChanging();
					this._Sao = value;
					this.SendPropertyChanged("Sao");
					this.OnSaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Han", DbType="NVarChar(50)")]
		public string Han
		{
			get
			{
				return this._Han;
			}
			set
			{
				if ((this._Han != value))
				{
					this.OnHanChanging(value);
					this.SendPropertyChanging();
					this._Han = value;
					this.SendPropertyChanged("Han");
					this.OnHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoi", DbType="NVarChar(50)")]
		public string Tuoi
		{
			get
			{
				return this._Tuoi;
			}
			set
			{
				if ((this._Tuoi != value))
				{
					this.OnTuoiChanging(value);
					this.SendPropertyChanging();
					this._Tuoi = value;
					this.SendPropertyChanged("Tuoi");
					this.OnTuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDD
		{
			get
			{
				return this._IDD;
			}
			set
			{
				if ((this._IDD != value))
				{
					this.OnIDDChanging(value);
					this.SendPropertyChanging();
					this._IDD = value;
					this.SendPropertyChanged("IDD");
					this.OnIDDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
